title: "Link"
tagline: "Simple, flexible link field type"
description: "Link is a field type that provides a robust method of linking to a variety of targets."
url: "https://flipboxfactory.com/software/link"
theme: "http://docs.flipboxfactory.com/v1"
google_analytics_tracking_id: "XX-XXXXXXXX-X"